### PR TITLE
DM-38383: LabJackAccelerometerDataClient: fix reporting of raw data

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Comment by r-owen** [comment]
I fixed the Jenkinsfile and Rob cleaned up the build. It's running now, so we'll see what happens.

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Review by wvreeven — APPROVED** [review]
Looks good to me.

**Pull request merged**
